Develop
VaretsaK/TeleBot pull request #1
Opened 2023-05-04 21:17 UTC by VaretsaK

2023-05-05 13:16 UTC, vladysllav requested changes
В цілому круто, але можна покращити

2023-05-05 13:16 UTC, vladysllav commented on main.py
> +        except IndexError:
В тебе вже є перевірка що елементів 2, індекс еррор ти не зможешь ніяк отримати, і якщо ти вже перевірив, то навіщо context.args[-1] використовувати, просто context.args[1] зроби і все

2023-05-05 13:16 UTC, vladysllav commented on main.py
> +        except IndexError:
Теж саме що і вище

2023-05-05 13:16 UTC, vladysllav commented on main.py
> +@save_file_decor
В тебе функція run постійно працює, тобто декоратор на виході не відпрацбовує, потрібно зберігати та вигружати дані іншим чином, бо закінчити виконання програми можна лише вимкнувши, що визове KeyboardInterrupt, можна це відловити(почитай як краще, там є своє механіки)

Або просто зберігати і доставати значення при визові команд

2023-05-05 13:16 UTC, vladysllav commented on main.py
> +    def __init__(self, amount: int, category: str, time=datetime.now()):
Не можна datetime.now() додавати до дефолтних значень, бо вона виконається лише 1 раз під час інтерпритації програми, тобто time для всіх твоїх обʼєктів буде однаковий.

Концепція з класом цікава, але якщо ти з ним потім працюєшь можешь зробити методи add щоб не amount явно вказувати у коді а просто робити + між обьектами Money

2023-05-06 23:00 UTC, VaretsaK commented on main.py
> +    def __init__(self, amount: int, category: str, time=datetime.now()):
Стосовно пункту з методом add у класі нічого не змінив, тому що саме додавання об'єктів у мене не відбувається, я лише виконую додавання атрибуту об'єктів до числового значення тим самим отримуючи потрібну мені суму. І виконую такі дії лише 3 рази у всій програмі.
Якщо ж додати метод add до класу, то знадобиться всі об'єкти спочатку покласти у новий список а потім додавати, можливо ще додавши якусь додаткову перевірку наших категорій і змінивши при всьому цьому метод str нашого класу...здається виходить складніше...принаймні для цього коду.

2023-06-05 12:42 UTC, merged